const texts = {
  _gender: [
    'm',
    'f'
  ],
  _preadj: [
    '',
    'nada',
    'poco',
    'algo',
    'muy',
    'extremadamente'
  ],
  _adjective: [
    'abierto',
    'agradable',
    'alegre',
    'amable',
    'ambicioso',
    'amistoso',
    'ansioso',
    'anticuado',
    'apático',
    'astuto',
    'atento',
    'audaz',
    'aventurero',
    'bien intencionado',
    'brusco',
    'bullicioso',
    'cauteloso',
    'cínico',
    'compasivo',
    'concienzudo',
    'condescendiente',
    'confiado',
    'considerado',
    'coqueto',
    'crítico',
    'cruel',
    'curioso',
    'deprimido',
    'desagradable',
    'descarado',
    'desconsiderado',
    'desequilibrado',
    'despistado',
    'diligente',
    'diplomático',
    'dramático',
    'dulce',
    'egoísta',
    'ególatra',
    'emocional',
    'encantador',
    'engreído',
    'entusiasta',
    'equilibrado',
    'estoico',
    'exaltado',
    'excitable',
    'exigente',
    'extravagante',
    'fanático',
    'fiel',
    'filosófico',
    'franco',
    'frío',
    'generoso',
    'gracioso',
    'hipercrítico',
    'impaciente',
    'impetuoso',
    'impredecible',
    'impulsivo',
    'inestable',
    'ingenioso',
    'ingenuo',
    'inquieto',
    'insensible',
    'intolerante',
    'inventivo',
    'irritable',
    'juguetón',
    'malévolo',
    'malhumorado',
    'mandón',
    'maquiavélico',
    'melancólico',
    'melodramático',
    'meticuloso',
    'metódico',
    'miserable',
    'modesto',
    'motivado',
    'obediente',
    'odioso',
    'orgulloso',
    'osco',
    'pacífico',
    'paranoico',
    'pasivo-agresivo',
    'pensativo',
    'perezoso',
    'perspicaz',
    'pomposo',
    'positivo',
    'predispuesto',
    'reacio',
    'recatado',
    'resentido',
    'respetuoso',
    'romántico',
    'ruidoso',
    'sensible',
    'sentimental',
    'servicial',
    'simpático',
    'snob',
    'sofisticado',
    'sombrío',
    'suspicaz',
    'talentoso',
    'temperamental',
    'tolerante',
    'valeroso',
    'valiente',
    'voluntarioso'
  ],

  _class: [
    {
      name: 'Bárbaro',
      body: '3',
      mind: '0',
      soul: '0',
      type: 'fighter'
    },
    {
      name: 'Guerrero',
      body: '2',
      mind: '0',
      soul: '1',
      type: 'fighter'
    },
    {
      name: 'Paladín',
      body: '2',
      mind: '1',
      soul: '0',
      type: 'fighter'
    },
    {
      name: 'Pícaro',
      body: '1',
      mind: '0',
      soul: '2',
      type: 'rogue'
    },
    {
      name: 'Ladrón',
      body: '0',
      mind: '0',
      soul: '3',
      type: 'rogue'
    },
    {
      name: 'Bardo',
      body: '0',
      mind: '1',
      soul: '2',
      type: 'rogue'
    },
    {
      name: 'Mago',
      body: '0',
      mind: '2',
      soul: '1',
      type: 'mentalist'
    },
    {
      name: 'Clérigo',
      body: '1',
      mind: '2',
      soul: '0',
      type: 'mentalist'
    },
    {
      name: 'Hechicero',
      body: '0',
      mind: '3',
      soul: '0',
      type: 'mentalist'
    },
    {
      name: 'Guardabosques',
      body: '1',
      mind: '1',
      soul: '1',
      type: 'rogue'
    }
  ],

  _race: [
    {
      name: 'Dracónido',
      size: 'large'
    },
    {
      name: 'Elfo',
      size: 'medium'
    },
    {
      name: 'Enano',
      size: 'small'
    },
    {
      name: 'Mediano',
      size: 'small'
    },
    {
      name: 'Tiflin',
      size: 'medium'
    },
    {
      name: 'Humano',
      size: 'medium'
    },
    {
      name: 'Semielfo',
      size: 'medium'
    },
    {
      name: 'Semiorco',
      size: 'large'
    },
    {
      name: 'Halfing',
      size: 'small'
    },
    {
      name: 'Gnomo',
      size: 'small'
    }
  ],

  _location: [
    'un pequeño pueblo',
    'la montaña más pequeña del mundo',
    'las alcantarillas de la ciudad',
    'una rotonda de Castellón que no recueda',
    'una familia numerosa',
    'un orfanato de payasos',
    'un pueblo donde solo intercambian bienes',
    'una educación super religiosa',
    'una caverna oscura y sin ecos',
    'una comuna de goblins',
    'el desierto húmedo',
    'una pequeña granja familiar',
    'un pueblo sin taberna',
    'una empresa de mercenarios',
    'una red subterránea de cuevas de dragones',
    'una ciudad nocturna',
    'una ciudad que nunca durmió',
    'un linaje real',
    'un espectáculo itinerante de carnaval',
    'un linaje de sangre impura',
    'un monasterio estricto',
    'una pandilla callejera',
    'un pantano ahora seco',
    'una ciudad en ruinas',
    'un castillo encantado',
    'la mejor biblioteca de la ciudad',
    'una ciudad bulliciosa',
    'una prisión de máxima seguridad',
    'una ciudad flotante',
    'una ciudad subterránea',
    'una compañía de teatro',
    'la academia de los guardias',
    'una pequeña taberna de un pueblo fronterizo',
    'el banco real',
    'una mercería de ropa para prostitutas goblins',
    'la oficina de correos de la ciudad',
    'una banda itinerante de ladornes',
    'un pueblo de pescadores',
    'un internado para los hijos de magos de clase media',
    'la base de un volcán',
    'un bosque ilusorio',
    'un monasterio élfico olvidado',
    'unas islas infestadas de piratas',
    'un asilo para enfermos de locura',
    'un reino caído',
    'los barrios pobres de la ciudad',
    'un monasterio submarino',
    'un pueblo minero',
    'un burdel de clase alta',
    'un circo nómada',
    'una ciudad turística en las montañas',
    'el peor burdel de la ciudad',
    'las tierras libres',
    'una casa de trabajo para niños',
    'la parte bonita de una ciudad mala',
    'una tranquila ciudad costera',
    'una escuela de magos pomposos',
    'un pequeño pueblo remoto',
    'un antiguo monasterio',
    'una provincia muy pequeña',
    'la torre de los huesos',
    'una sucesión de lugares terribles para vivir',
    'una mazmorra famosa en los barrios bajos',
    'la bodega de un barco de esclavos',
    'los barrios pobres de una ciudad portuaria',
    'un tranquilo pueblo de playa',
    'un lugar que solo ellos pueden pronunciar',
    'un templo extremista',
    'el gremio de cazadores de ratas',
    'una crianza sobreprotectora',
    'una ciudad hundida en una cienaga',
    'las tierras secas',
    'una ciudad en las arenas movedizas',
    'el más vil de los pantanos',
    'un paraíso tropical',
    'un pueblo en un volcán recién erupcionado',
    'una pequeña panadería familiar',
    'un pequeño pueblo donde nunca pasaba nada',
    'un bastión militar subterráneo',
    'un pueblo de forajidos',
    'una ciudad asolada por la guerra',
    'una ciudad repleta de plagas',
    'una pobre granja lechera',
    'la taberna local',
    'las heladas tierras del norte',
    'las montañas polvorientas',
    'un monasterio aislado',
    'los interminables campos de maíz',
    'una prisión en una colonia de ultramar',
    'de una ciudad profunda debajo de las montañas',
    'las tierras baldías del norte',
    'una cervecería local',
    'la escuela de magos de un pequeño pueblo',
    'un pueblo en un bosque aislado',
    'una ciudad del desierto escondida dentro de una tormenta de arena',
    'un viñedo rico',
    'una jungla congelada',
    'los barrios pobres de la ciudad',
    'una ciudad de chabolas flotante',
    'un pueblo junto al acantilado',
    'una isla en movimiento',
    'un pueblo maldito',
    'una tranquila choza del bosque',
    'el mar de arena',
    'una isla pensada para estar deshabitada',
    'las grandes minas abandonadas',
    'un pequeño pueblo en la frontera',
    'una próspera ciudad portuaria',
    'una ciudad destruida',
    'las llanuras del norte',
    'el mar de iceberg',
    'las tierras baldías',
    'un pequeño pueblo pintoresco en una colina',
    'una ciudad conquistada por los orcos',
    'las cocinas de los cuarteles locales',
    'un campo de internamiento para gordos',
    'una pequeña granja en los pastizales',
    'el bosque sin árboles',
    'un bullicioso reino subterráneo',
    'una ciudad submarina que está seca por un campo de fuerza mágica',
    'la línea sucesoria de la familia más fuerte de la tierra',
    'las catacumbas reales',
    'una falsa colonia de leprosos que esconde un secreto',
    'una casa de descanso',
    'La Ciudad de las Diez Mil Banderas',
    'un mercado de esclavos',
    'una ciudad de la que nadie más ha oído hablar',
    'un campamento de seguidores del ejército',
    'una fortaleza enana condenada',
    'una ciudad con torres que rivalizan con las nubes',
    'la corte del rey del reino rival',
    'una península con niebla permanente',
    'un gremio secreto de luchadores',
    'una familia aristocrática y endogámica',
    'una empresa de tala forestal encantada',
    'las llanuras chamuscadas',
    'la cordillera de hierro',
    'el calabozo negro',
    'una poderosa ciudad comercial',
    'los alrededores pobres de la ciudad capital',
    'la línea sucesoria de una realeza caída',
    'escuela de navegación para ciegos',
    'un pueblo sin hijos',
    'el desierto cambiante',
    'los bosques de sombra',
    'el gremio de asesinos',
    'una fortaleza abandonada',
    'una isla a la que no se puede llegar en barco',
    'los desperdicios sin fin',
    'un desierto congelado',
    'una comuna de pensadores libres',
    'una ciudad portuaria adormecida',
    'La cordillera destrozada por dragones',
    'una familia de caballeros en desgracia',
    'la vigilancia de la ciudad',
    'un campo de refugiados para huérfanos de guerra',
    'una gran metrópolis del desierto',
    'un orfanato mal dirigido',
    'un mercado de la ciudad bulliciosa',
    'una mansión en ruinas',
    'un instituto de jóvenes delincuentes',
    'un desierto hecho por el hombre',
    'una caravana de esclavos',
    'una casa de juego de clase alta',
    'una granja asolada por la sequía',
    'una noble familia ahora empobrecida',
    'el control de calidad para la asociación de elaboración de pociones',
    'una ciudad donde los orcos se compran y venden como esclavos',
    'una orden secreta de monjes',
    'el ejercito imperial'
  ],

  _names: [
    'Lexand Horne',
    'Munder',
    'Harder',
    'Pholes',
    'Thelry',
    'Wilher',
    'Aeweald',
    'Wulfa',
    'Here',
    'Jamart',
    'Raffin',
    'Tondbeorht',
    'Anied',
    'Iged',
    'Yodwin',
    'Eadulf',
    'Helwy',
    'Ralphye Gare',
    'Rewill',
    'Edfrith',
    'Rewill Kesell',
    'Reyny',
    'Wulfa',
    'Goda',
    'Rebert',
    'Robern Vinte',
    'Ryany',
    'Driffolk',
    'Eaddaf',
    'Helmund',
    'Brither',
    'Ether',
    'Mesym Woode',
    'Dere',
    'Walteph Page',
    'Altel',
    'Bertio',
    'Oswulf',
    'Igelm',
    'Nathye',
    'Reder',
    'Monder',
    'Wisym',
    'Lany Caney',
    'Artis',
    'Wine',
    'Werher',
    'Lesym',
    'Cheny Parry',
    'Wulffre'
  ],

  _backstory: [
    'no cree en la magia, nunca',
    'odia usar sus lentes',
    'le resulta imposible hablar al otro sexo',
    'siempre ha querido abrir su propia taberna',
    'tiene una enorme deuda que pagar',
    'se crió por fantasmas',
    'sufre de claustrofobia',
    'realmente le tiene miedo a la oscuridad',
    'hace chistes inapropiados en los peores momentos',
    'tiene miedo a las alturas',
    'no entiende el concepto de cortesía',
    'tiene un problema severo de ludopatía',
    'le dijeron que nunca llegaría a nada',
    'quiere caer bien a todo el mundo',
    'nunca se quita la armadura, por si acaso',
    'siempre quiere ser el centro de atención',
    'estudió diseño de interiores de mazmorras',
    'es muy racista hacia los esqueletos vivos',
    'cree que desciende de los dioses, pero aún no ha descubierto quién es su padre',
    'está escribiendo una autobiografía',
    'tiene serios problemas con papá',
    'tiene un problema con la bebida',
    'es completamente invidente al color',
    'vio a toda su familia consumida por un cubo gelatinoso',
    'siente ansiedad hablando frente a multitudes',
    'tiene miedo de los bordes afilados',
    'no tiene reflejo',
    'sufre de hemorragias nasales',
    'no puede nadar',
    'se crió para ser bibliotecario',
    'creció en un cementerio',
    'tiene miedo del fuego',
    'odia la música',
    'desconfía de toda autoridad',
    'desconfía de alguien más pequeño',
    'odia la monarquía',
    'le tiene miedo a los perros',
    'tiene problemas de ira',
    'no puede leer, de ninguna manera',
    'desertó del ejército',
    'es responsable de la muerte de su hermana',
    'sabe a ciencia cierta que sus días están contados',
    'medita antes del amanecer',
    'vigila constantemente su espalda',
    "siempre se refiere a objetos inanimados como 'ella'",
    'siempre cumple sus promesas',
    'se está rehabilitando de su canibalismo, aunque no va muy bien',
    'quiere ser una celebridad, pase lo que pase',
    'está tratando de salir del negocio de las aventuras para asentarse',
    'se deleita en identificar nuevas especies de escarabajos',
    'tiene serios problemas de higiene corporal',
    'se está rehabilitando de su ludopatía',
    'no soporta ver sangre',
    'en secreto se metío en aventuras para impresionar a su amante',
    'tiene miedo de que el resto del grupo le mate si intenta irse',
    'busca sin cesar a su hijo secuestrado',
    'preferiría matarte antes que hacer contacto visual',
    'tiene veintisiete hermanos para alimentar',
    'no tiene nada que perder',
    'no conoce su propia fuerza',
    'lleva el cráneo de su mejor amigo',
    'tiene un serio fetiche de armas',
    'ha hecho voto de silencio',
    'sólo trata de sobrevivir',
    'está tratando de evitar una profecía',
    'quiere borrar su nombre',
    'no cree en la higiene',
    'es perseguido por un terrible monstruo',
    'se está muriendo de una plaga y busca una cura',
    'perdió a su familia en un ataque de dragón',
    'lucha por los derechos de los no muertos',
    'una vez sobrevivió a un caldero hirviendo',
    'no puede soportar el silencio',
    'no puedo dormir en el interior',
    'solo duerme con las luces encendidas',
    'odia estar limpio',
    'hizo de borrachera un juramento de sangre y olvidó para qué',
    'no percibe género',
    'se dio cuenta de la importancia de la alfabetización demasiado tarde en la vida',
    'mantiene una lista negra',
    'perdió su sombra en una apuesta',
    'ha engañado a la muerte más veces de las que merece',
    'encuentra la armadura demasiado restrictiva',
    'no tiene sentido del olfato',
    'se niega a bañarse',
    'es intolerante a la lactosa',
    'agrega una muesca a su espada cada noche',
    'piensa que puede leer el futuro, pero siempre se equivoca',
    'tiene un miedo irracional a los gatos',
    'es total y absolutamente incapaz de oir',
    'está huyendo de un matrimonio arreglado por sus padres',
    'conoce siete secretos peligrosos',
    'tiene un miedo debilitante a los espacios abiertos',
    'siempre habla en tercera persona',
    'está buscando una hierba de fertilidad rara',
    'odia la palabra escrita',
    'quiere algún día poseer su propio barco',
    'tiene una orden de arresto pendiente por su detención',
    'fue repudiado por su familia',
    'incendió accidentalmente el templo local y ahora es su dios le maldice',
    'lleva un mapa de tesoro críptico que ganó en una apuesta de taberna',
    'ha sido exiliado dos veces bajo nombres diferentes',
    'cree que tiene derecho al trono',
    'ha estado huyendo durante más de tres años',
    'le aterran las ratas',
    'cree que a los muertos vivientes se les debe dar una segunda oportunidad',
    'vio como ejecutaban a su familia',
    'no soporta a los niños',
    'odia el contacto físico',
    'perdió su sentido del olfato en una pelea de bar',
    'le gusta hablar en rima',
    'lucha por la igualdad de especies',
    'sufrio una petrificación durante más de doscientos años',
    'tiene algunas conexiones bastante sombrías',
    'comenzó una rebelión en las montañas del norte',
    'toma todas las decisiones menores lanzando una moneda',
    'siempre se ve lo mejor posible',
    'solía ​​trabajar como segurata de una taberna',
    'odia montar a caballo',
    'no entiende el sarcasmo',
    'sufre de terrores nocturnos',
    "nunca deja pasar la oportunidad de decir 'te lo dije'",
    'fue acusado por el asesinato de un posadero famoso y muy querido',
    'cree en la pureza racial',
    'está huyendo después de tener un romance con el hijo de un noble',
    'no ha estado del todo bien desde el accidente',
    'no ha logrado nada en su corta vida todavía',
    'perdió sus orejas hace mucho tiempo',
    'tiene un odio ardiente por los piratas',
    'tiene como objetivo aprender todos los idiomas en la tierra',
    'le debe dinero a las personas equivocadas',
    'cree en el ojo por ojo',
    'nunca pone la otra mejilla',
    'una vez sirvió como un bufón de la corte',
    'ahora sabe que fue mala idea haberse tatuado el mapa del tesoro',
    'ya hecho y perdido una fortuna',
    'tiene un poema para todas las ocasiones',
    'entró en el ejército a los catorce',
    'tiene un problema de sonambulismo regular',
    'fue aprendiz de un alquimista fallecido',
    'se hace pasar por otra persona',
    'está escribiendo un poema épico sobre la aventura del grupo',
    'le encanta regatear',
    'sufre de una pesadilla recurrente',
    'necesita ganarse la confianza de un duque odiado',
    'salió del retiro para esta aventura',
    'saquea cada muerte pero deja lo suficiente para pagar por su entierro',
    'despertó en un bar sin memoria y con una carta sellada',
    'diseñaba trampas para mazmorras',
    'tiene delirios de grandeza',
    'sólo quiere recuperar su dinero',
    'siempre quiso ser artista',
    'cree que la armadura de la placa es solo un signo de ser elegante y privilegiado',
    'no pudo proteger a la familia real',
    'le gusta resolver argumentos con un pulso',
    'nunca devolvió nada de lo que pidieron prestado',
    'le cortaron la nariz en un duelo',
    'nació en un cuerpo diferente',
    'sufre de vértigo',
    'perdió dos dedos en un accidente entrenando',
    'está rastreando el tesoro que su padre muerto trató de encontrar',
    'lleva un medallón encantado que no puede abrir',
    'se está haciendo demasiado mayor para todo esto',
    'rechazó la propuesta de matrimonio de un príncipe extranjero',
    "tiene la mala costumbre de hacer bromas 'divertidas' después de cada muerte",
    'tiene dientes de madera después de un incidente con la maza',
    'odia tener que esperar',
    'está buscando el conocimiento de la verdadera inmortalidad',
    'perdió a su mejor amigo en una emboscada',
    'actualmente se encuentra en libertad condicional por embriaguez y alteración del orden',
    'está planeando retirarse el próximo año',
    'exagera todo de lo que hablan',
    'no tiene concepto de espacio personal',
    'es realmente hábil sobornando a los funcionarios',
    'nunca se ha cortado el pelo',
    'solo quedan dos años más hasta que un demonio regrese para reclamar su alma',
    'se busca una recompensa por su cabeza',
    'usa un collar misterioso que aleatoriamente hace ruido',
    'ya no está técnicamente con vida',
    'no habla una palabra de común'
  ]

}

const read = (item) => item[Math.floor(Math.random() * item.length)]

export const pjGenerator = () => {
  let _gender = read(texts._gender)
  let _class = read(texts._class)
  let _race = read(texts._race)
  let _preadj = read(texts._preadj)
  let _adj = read(texts._adjective)
  let _loc = read(texts._location)
  let _name = read(texts._names)
  let _surname = read(texts._names)
  let _history = read(texts._backstory)
  let _pre = 'Un'

  if (_gender === 'f') {
    _pre = 'Una'
    if (_class.name.substring(_class.name.length - 1) === 'o') _class.name = _class.name.substring(0, _class.name.length - 1) + 'a'
    if (_class.name.substring(_class.name.length - 2) === 'ón') _class.name = _class.name.substring(0, _class.name.length - 2) + 'ona'
    if (_race.name.substring(_race.name.length - 1) === 'o') _race.name = _race.name.substring(0, _race.name.length - 1) + 'a'
    if (_adj.substring(_adj.length - 1) === 'o') _adj = _adj.substring(0, _adj.length - 1) + 'a'
    if (_adj.substring(_adj.length - 2) === 'or') _adj = _adj.substring(0, _adj.length - 2) + 'ora'
    if (_adj.substring(_adj.length - 2) === 'ón') _adj = _adj.substring(0, _adj.length - 2) + 'ona'
  }

  let de = (_loc.indexOf('el') === 0) ? 'd' : 'de '
  let _desc = `${_pre} ${_class.name} ${_race.name} ${_preadj} ${_adj} ${de}${_loc}, que ${_history}`

  if (_race.size === 'small') _class.body--
  if (_race.size === 'small') _class.soul++
  if (_race.size === 'large') _class.body++
  if (_race.size === 'large') _class.soul--

  return {
    'active': false,
    'body': _class.body,
    'class': _class.name,
    'type': _class.type,
    'description': _desc,
    'equip': '',
    'level': '1',
    'mind': _class.mind,
    'name': `${_name} ${_surname}`,
    'race': _race.name,
    'size': _race.size,
    'skills': '',
    'soul': _class.soul,
    'stress': 11 + parseInt(_class.body),
    'wealth': '2'
  }
}
